(env
 (dev
  (flags :standard -w -9)))

(test
 (name test_bot_info)
 (libraries alcotest bot-components base))

(test
 (name test_webhook)
 (libraries alcotest bot-components base cohttp))

(test
 (name repo_config_test)
 (libraries base bot-components config alcotest)
 (modules repo_config_test_helpers repo_config_test))

(test
 (name repo_config_error_test)
 (libraries base bot-components config alcotest)
 (modules repo_config_test_helpers repo_config_error_test))

(test
 (name repo_config_property_test)
 (libraries base bot-components config alcotest qcheck-alcotest)
 (modules repo_config_property_test))
