(env
 (dev
  (flags :standard -w -9)))

(library
 (name test_helpers)
 (modules test_helpers)
 (wrapped false)
 (libraries bot-components base))

(test
 (name test_bot_info)
 (modules test_bot_info)
 (libraries alcotest bot-components base test_helpers))

(test
 (name test_webhook)
 (modules test_webhook)
 (libraries alcotest bot-components base cohttp))

(test
 (name test_config)
 (modules test_config)
 (libraries alcotest bot-components coq-bot.utils coq-bot.config base unix
   test_helpers))

(test
 (name test_repo_config)
 (modules test_repo_config)
 (libraries alcotest bot-components coq-bot.config base))

(test
 (name test_pat_usage)
 (modules test_pat_usage)
 (libraries alcotest bot-components coq-bot.utils base test_helpers))

(test
 (name test_minimize_parser)
 (modules test_minimize_parser)
 (libraries alcotest bot-components base))

(test
 (name test_git_utils)
 (modules test_git_utils)
 (libraries alcotest bot-components base))

(test
 (name test_string_utils)
 (modules test_string_utils)
 (libraries alcotest bot-components base))

(test
 (name test_bench)
 (modules test_bench)
 (libraries alcotest bot-components coq-bot.utils base))