open Bot_components
open Base

(* The bot supports two authentication methods:
   1. GitHub App: Uses installation tokens generated by GitHub App
   2. PAT/Legacy (will be removed): Uses Personal Access Token *)

(* When both tokens exist, use GitHub App installation token (not PAT) *)
let test_uses_github_app_token_when_available () =
  let bot_info =
    { Bot_info.github_pat= "legacy_pat"
    ; github_install_token= Some "install_token_123"
    ; github_name= "testbot"
    ; email= "test@example.com"
    ; domain= "test.com"
    ; gitlab_instances= Hashtbl.create (module String)
    ; app_id= 12345 }
  in
  let token = Bot_info.github_token bot_info in
  Alcotest.(check string) "uses installation token" "install_token_123" token

(* When no installation token exists, fall back to PAT (legacy behavior) *)
let test_falls_back_to_pat_when_no_installation_token () =
  let bot_info =
    { Bot_info.github_pat= "legacy_pat"
    ; github_install_token= None (* No GitHub App token available *)
    ; github_name= "testbot"
    ; email= "test@example.com"
    ; domain= "test.com"
    ; gitlab_instances= Hashtbl.create (module String)
    ; app_id= 12345 }
  in
  let token = Bot_info.github_token bot_info in
  (* Currently falls back to PAT - this is the legacy behavior we're removing
     TODO: After PAT removal, this should fail with an error instead *)
  Alcotest.(check string) "falls back to PAT" "legacy_pat" token

let () =
  Alcotest.run "Bot_info tests"
    [ ( "github_token"
      , [ ( "uses GitHub App token when available"
          , `Quick
          , test_uses_github_app_token_when_available )
        ; ( "falls back to PAT when no installation token (legacy - will be \
             removed)"
          , `Quick
          , test_falls_back_to_pat_when_no_installation_token ) ] ) ]
