open Bot_components
open Base

(* The bot supports two authentication methods:
   1. GitHub App: Uses installation tokens generated by GitHub App
   2. PAT/Legacy (will be removed): Uses Personal Access Token *)

(* When installation token exists, use GitHub App installation token *)
let test_uses_github_app_token_when_available () =
  let bot_info =
    { Bot_info.github_install_token= Some "install_token_123"
    ; github_name= "testbot"
    ; email= "test@example.com"
    ; domain= "test.com"
    ; gitlab_instances= Hashtbl.create (module String)
    ; app_id= 12345 }
  in
  let token = Bot_info.github_token bot_info in
  Alcotest.(check string) "uses installation token" "install_token_123" token

let () =
  Alcotest.run "Bot_info tests"
    [ ( "github_token"
      , [ ( "uses GitHub App token when available"
          , `Quick
          , test_uses_github_app_token_when_available ) ] ) ]
